spring:
  datasource:
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:mysql://localhost:3306/spring_test}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
    initialize: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
